version: "3"

services:

  adminer:
    image: adminer:4.7.7
    container_name: adminer
    environment:
      - VIRTUAL_HOST=adminer.domain.test
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=adminer.domain.test
      - LETSENCRYPT_EMAIL=email@domain.test
    expose:
      - "8080"

networks:
  default:
    external:
      name: nginx-proxy